# This file is machine-generated - editing it directly is not advised

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[Distributed]]
deps = ["Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[DynamicPolynomials]]
deps = ["LinearAlgebra", "MultivariatePolynomials", "Pkg", "Reexport", "Test"]
git-tree-sha1 = "d5f0b3b68d3359d629742406579862a1407d9548"
repo-rev = "st/unique-polyvar"
repo-url = "DynamicPolynomials"
uuid = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
version = "0.1.4"

[[FixedPolynomials]]
deps = ["LinearAlgebra", "MultivariatePolynomials", "Test"]
git-tree-sha1 = "32ec33fe4387eb165461b7141d4be732097086ad"
uuid = "3dd14ad9-0029-526e-86e9-8aa0bdd2ab0d"
version = "0.4.0"

[[HomotopyContinuation]]
deps = ["DynamicPolynomials", "FixedPolynomials", "LinearAlgebra", "MultivariatePolynomials", "Printf", "ProgressMeter", "ProjectiveVectors", "Random", "StaticArrays", "StaticPolynomials", "Test", "TreeViews"]
git-tree-sha1 = "f501b6a65b9fb5b62c525185e4ea572644ca98c0"
repo-rev = "unqiue-points-group-actions"
repo-url = "HomotopyContinuation"
uuid = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
version = "0.6.1"

[[InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[LibGit2]]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[MultivariatePolynomials]]
deps = ["LinearAlgebra", "Test"]
git-tree-sha1 = "f88a674a9857b7ecda5adc405b8353f19ea0ac46"
repo-rev = "master"
repo-url = "MultivariatePolynomials"
uuid = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
version = "0.2.8+"

[[Pkg]]
deps = ["Dates", "LibGit2", "Markdown", "Printf", "REPL", "Random", "SHA", "UUIDs"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[ProgressMeter]]
deps = ["Distributed", "Printf", "Random", "Test"]
git-tree-sha1 = "37e7d3982c8d4610196829c01387dd561756aedc"
uuid = "92933f4c-e287-5a05-a399-4b506db050ca"
version = "0.8.0"

[[ProjectiveVectors]]
deps = ["LinearAlgebra", "StaticArrays", "Test"]
git-tree-sha1 = "548929157a99e72efc747fd396402c03ecdb7784"
uuid = "01f381cc-face-5a0a-ade9-ef63dc65d628"
version = "0.2.2"

[[REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[Reexport]]
deps = ["Pkg"]
git-tree-sha1 = "7b1d07f411bc8ddb7977ec7f377b97b158514fe0"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "0.2.0"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[StaticArrays]]
deps = ["InteractiveUtils", "LinearAlgebra", "Random", "Statistics", "Test"]
git-tree-sha1 = "3841b39ed5f047db1162627bf5f80a9cd3e39ae2"
uuid = "90137ffa-7385-5640-81b9-e52037218182"
version = "0.10.3"

[[StaticPolynomials]]
deps = ["LinearAlgebra", "MultivariatePolynomials", "StaticArrays"]
git-tree-sha1 = "4e4a8c7d85f47ff19e4c4a4d2bc4a5cda7781e8b"
repo-rev = "st/hessian"
repo-url = "StaticPolynomials"
uuid = "62e018b1-6e46-5407-a5a7-97d4fbcae734"
version = "1.2.0"

[[Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[Test]]
deps = ["Distributed", "InteractiveUtils", "Logging", "Random"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[TreeViews]]
deps = ["Test"]
git-tree-sha1 = "8d0d7a3fe2f30d6a7f833a5f19f7c7a5b396eae6"
uuid = "a2a6695c-b41b-5b7d-aed9-dbfdeacea5d7"
version = "0.3.0"

[[UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
